checkpoint_dir: 'dl_proj/checkpoints'
device: 'mps'
seed: 104
require_early_stop: true
early_stop_desc: true
early_stopping_min_delta: 0.001
early_stopping_patience: 5

# Training configs
batch_size: 128
num_epochs: 50
lr: 5e-4

# Synthetic Dataset configs
n_samples: 16384
val_samples: 1024
test_samples: 128
vocab_size: 128
max_len: 196

# Model configs
embedding_dim: 128
heads: 4
d_k: 32
d_v: 32
expansion_factor: 1
dropout: 0.1
attn_dropout: 0.1
causal_mask: true
self_attn_mask: true
depth: 1

# Attention type (full or lsh)
attn_type: 'lsh'

# Reformer Model Configs (useful only for lsh models)
bucket_size: 28
n_rounds: 4
#####################################################

# Names
experiment_name: 'synth-gen-lsh-r4-new'